"""add options column to scans table

Revision ID: bc7b925e44f4
Revises: 001
Create Date: 2025-11-11 08:16:52.353187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7b925e44f4'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_analyses_agent_type', table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_scan_id', table_name='ai_analyses')
    op.drop_constraint('ai_analyses_scan_id_fkey', 'ai_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analyses', 'scans', ['scan_id'], ['id'])
    op.add_column('scans', sa.Column('options', sa.JSON(), nullable=True))
    op.drop_index('ix_scans_started_at', table_name='scans')
    op.drop_index('ix_scans_status', table_name='scans')
    op.drop_index('ix_vulnerabilities_scan_id', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_severity', table_name='vulnerabilities')
    op.drop_constraint('vulnerabilities_scan_id_fkey', 'vulnerabilities', type_='foreignkey')
    op.create_foreign_key(None, 'vulnerabilities', 'scans', ['scan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vulnerabilities', type_='foreignkey')
    op.create_foreign_key('vulnerabilities_scan_id_fkey', 'vulnerabilities', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_vulnerabilities_severity', 'vulnerabilities', ['severity'], unique=False)
    op.create_index('ix_vulnerabilities_scan_id', 'vulnerabilities', ['scan_id'], unique=False)
    op.create_index('ix_scans_status', 'scans', ['status'], unique=False)
    op.create_index('ix_scans_started_at', 'scans', ['started_at'], unique=False)
    op.drop_column('scans', 'options')
    op.drop_constraint(None, 'ai_analyses', type_='foreignkey')
    op.create_foreign_key('ai_analyses_scan_id_fkey', 'ai_analyses', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_ai_analyses_scan_id', 'ai_analyses', ['scan_id'], unique=False)
    op.create_index('ix_ai_analyses_agent_type', 'ai_analyses', ['agent_type'], unique=False)
    # ### end Alembic commands ###
